version: '3.8'
services:
  app:
    build: .
    image: strangeloop.cz/temperature-monitor
    container_name: temperature-monitor
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/db
    environment:
      - NODE_ENV=production 